name: GitHub Actions Demo
on: 
  push:
    branches:
      - main
      - master
  page_build:
    branches:
      - main
      - master
  
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: make dirhtml
      - run: cp -a _build/dirhtml/. ./docs
      - run: make clean
