name: Make Documentation
on: 
  push:
    branches:
      - main
      - master
  page_build:
    branches:
      - main
      - master
  
jobs:
  Make_Docs:
    runs-on: ubuntu-latest
    steps:
      - run: sphinx-build . ./docs/
      - run: make dirhtml
      - run: cp -a _build/dirhtml/. ./docs
      - run: make clean
